// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPQi8mCVdKiFeJyukTADYcPcabBo1tvi0',
    appId: '1:617164897888:web:869cddcbb9c933c4bacd05',
    messagingSenderId: '617164897888',
    projectId: 'todoapp-d495d',
    authDomain: 'todoapp-d495d.firebaseapp.com',
    storageBucket: 'todoapp-d495d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMr3XtFYj2vhpGSCqAfrR6MeR3bLR5Uas',
    appId: '1:617164897888:android:c02830463c29a403bacd05',
    messagingSenderId: '617164897888',
    projectId: 'todoapp-d495d',
    storageBucket: 'todoapp-d495d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV5LTjSTJTgph8Gu0lNSrEUNCeMovAh9M',
    appId: '1:617164897888:ios:6204cd687e463255bacd05',
    messagingSenderId: '617164897888',
    projectId: 'todoapp-d495d',
    storageBucket: 'todoapp-d495d.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV5LTjSTJTgph8Gu0lNSrEUNCeMovAh9M',
    appId: '1:617164897888:ios:8ed38c8d4dc0ebc1bacd05',
    messagingSenderId: '617164897888',
    projectId: 'todoapp-d495d',
    storageBucket: 'todoapp-d495d.appspot.com',
    iosBundleId: 'com.example.todoapp.RunnerTests',
  );
}
